<a href="https://colab.research.google.com/github/Rydzio/Machine-Learning/blob/main/Artificial_Neural_Network_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

Link to the picture:
https://drive.google.com/file/d/1PfDfForXZd0_kOp2G2Box4BvEhN_HIhc/view?usp=share_link

Now we need to copy JUST the image id:
1PfDfForXZd0_kOp2G2Box4BvEhN_HIhc

We will use this base link to generate your link with the image id:
https://drive.google.com/uc?export=view&id=your_id

We then copy the id in the link:
https://drive.google.com/uc?export=view&id=1PfDfForXZd0_kOp2G2Box4BvEhN_HIhc

Finally, to place as an image in Google Colab:
![](https://drive.google.com/uc?export=view&id=1PfDfForXZd0_kOp2G2Box4BvEhN_HIhc
)

In [ ]:
![](https://drive.google.com/uc?id=1PfDfForXZd0_kOp2G2Box4BvEhN_HIhc)

/bin/bash: -c: line 0: syntax error near unexpected token `https://drive.google.com/uc?id=1PfDfForXZd0_kOp2G2Box4BvEhN_HIhc'
/bin/bash: -c: line 0: `[](https://drive.google.com/uc?id=1PfDfForXZd0_kOp2G2Box4BvEhN_HIhc)'


### Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
tf.__version__

'2.11.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount = True)

Mounted at /content/gdrive/


In [ ]:
data = '/content/gdrive/MyDrive/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Bonus - Artificial Neural Networks (ANN) for Regression/Dataset/Folds5x2_pp.xlsx'
dataset = pd.read_excel(data)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=0)

In [ ]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [ ]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [ ]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [ ]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
# if doing classification with only two categories (yes/no) -> activation = 'sigmoid'
# if doing classification with more than two categories -> activation = 'softmax'
# if doing regression -> no activation function
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss='mean_squared_error')
# for stochastic gradient descent -> optimizer='adam'
# for regression -> loss='mean_squared_error'

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 3s 4ms/step - loss: 36374.9180
Epoch 2/100
240/240 [==============================] - 1s 4ms/step - loss: 287.9074
Epoch 3/100
240/240 [==============================] - 1s 3ms/step - loss: 277.1739
Epoch 4/100
240/240 [==============================] - 1s 3ms/step - loss: 263.9195
Epoch 5/100
240/240 [==============================] - 1s 4ms/step - loss: 248.1610
Epoch 6/100
240/240 [==============================] - 1s 5ms/step - loss: 230.8770
Epoch 7/100
240/240 [==============================] - 2s 6ms/step - loss: 211.8290
Epoch 8/100
240/240 [==============================] - 1s 6ms/step - loss: 192.0406
Epoch 9/100
240/240 [==============================] - 1s 4ms/step - loss: 172.0952
Epoch 10/100
240/240 [==============================] - 1s 3ms/step - loss: 151.5406
Epoch 11/100
240/240 [==============================] - 1s 3ms/step - loss: 132.0096
Epoch 12/100
240/240 [==============================] - 1s 2ms/step - lo

### Predicting the results of the Test set

In [ ]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

60/60 [==============================] - 0s 1ms/step
[[431.37 431.23]
 [462.38 460.01]
 [465.86 461.14]
 ...
 [473.11 473.26]
 [439.91 438.  ]
 [459.1  463.28]]
